# Generated by Django 3.2 on 2022-11-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_rename_cars_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='Body',
            new_name='body',
        ),
    ]
